version: '3'
services:
  postgres:
    image: postgres:9.6.8-alpine
    container_name: konga-local-postgres-9.6.8
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: konga

  kong_migrations:
    image: kong:0.13.1-centos # can't use alpine with the wait-for-it script
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    entrypoint:
      - /wait-for-it.sh
      - --host=postgres
      - --port=5432
      - --
    command:
      - kong
      - migrations
      - up
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: root
      KONG_PG_DATABASE: konga
      KONG_PG_PASSWORD: supersecret
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    depends_on: 
      - postgres

  kong:
    image: kong:latest
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: root
      KONG_PG_PASSWORD: supersecret
      KONG_PG_DATABASE: konga
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444